package org.iesalandalus.programacion.matriculacion.vista;

public enum Opcion {
    SALIR("SALIR"),
    INSERTAR_ALUMNO("INSERTAR_ALUMNO"),
    BUSCAR_ALUMNO("BUSCAR_ALUMNO"),
    BORRAR_ALUMNO("BORRAR_ALUMNO"),
    MOSTRAR_ALUMNOS("MOSTRAR_ALUMNOS"),
    INSERTAR_CICLO_FORMATIVO("INSERTAR_CICLO_FORMATIVO"),
    BUSCAR_CICLO_FORMATIVO("BUSCAR_CICLO_FORMATIVO"),
    BORRAR_CICLO_FORMATIVO("BORRAR_CICLO_FORMATIVO"),
    MOSTRAR_CICLOS_FORMATIVOS("MOSTRAR_CICLOS_FORMATIVOS"),
    INSERTAR_ASIGNATURA("INSERTAR_ASIGNATURA"),
    BUSCAR_ASIGNATURA("BUSCAR_ASIGNATURA"),
    BORRAR_ASIGNATURA("BORRAR_ASIGNATURA"),
    MOSTRAR_ASIGNATURAS("MOSTRAR_ASIGNATURAS"),
    INSERTAR_MATRICULA("INSERTAR_MATRICULA"),
    BUSCAR_MATRICULA("BUSCAR_MATRICULA"),
    ANULAR_MATRICULA("ANULAR_MATRICULA"),
    MOSTRAR_MATRICULAS("MOSTRAR_MATRICULAS"),
    MOSTRAR_MATRICULAS_ALUMNO("MOSTRAR_MATRICULAS_ALUMNO"),
    MOSTRAR_MATRICULAS_CICLO_FORMATIVO("MOSTRAR_MATRICULAS_CICLO_FORMATIVO"),
    MOSTRAR_MATRICULAS_CURSO_ACADEMICO("MOSTRAR_MATRICULAS_CURSO_ACADEMICO");

    String cadenaAMostrar;

    Opcion(String cadenaAMostrar) {
        this.cadenaAMostrar=cadenaAMostrar;

    }

    @Override
    public String toString() {
        return ordinal() + " .- " + cadenaAMostrar;
    }
}
